-- Provisioning administrator only. No inherited runtime or authority rights.
BEGIN;
CREATE ROLE contour_catalog_worker NOLOGIN INHERIT NOSUPERUSER NOBYPASSRLS
    NOCREATEROLE NOCREATEDB NOREPLICATION;
CREATE ROLE contour_catalog_reader NOLOGIN INHERIT NOSUPERUSER NOBYPASSRLS
    NOCREATEROLE NOCREATEDB NOREPLICATION;
COMMIT;
